import * as Index from '@src/index'

test('Index', () => {
  const expectedExports: string[] = [
    'RuntimeError'
  , 'InvalidArgumentError'

  , 'countdown'
  , 'countup'
  , 'range'

  , 'chunkAsync'
  , 'chunkByAsync'
  , 'chunkBy'
  , 'chunk'
  , 'concatAsync'
  , 'concat'
  , 'dropAsync'
  , 'dropRightAsync'
  , 'dropRight'
  , 'dropUntilAsync'
  , 'dropUntil'
  , 'drop'
  , 'filterAsync'
  , 'filter'
  , 'flattenAsync'
  , 'flattenByAsync'
  , 'flattenBy'
  , 'flattenDeepAsync'
  , 'flattenDeep'
  , 'flatten'
  , 'mapAsync'
  , 'map'
  , 'repeatAsync'
  , 'repeat'
  , 'sliceAsync'
  , 'slice'
  , 'splitAsync'
  , 'splitByAsync'
  , 'splitBy'
  , 'split'
  , 'takeAsync'
  , 'takeRightAsync'
  , 'takeRight'
  , 'takeUntilAsync'
  , 'takeUntil'
  , 'take'
  , 'tapAsync'
  , 'tap'
  , 'toAsyncIterable'
  , 'transformAsync'
  , 'transform'
  , 'uniqAsync'
  , 'uniqByAsync'
  , 'uniqBy'
  , 'uniq'
  , 'zipAsync'
  , 'zip'

  , 'consume'
  , 'eachAsync'
  , 'each'
  , 'everyAsync'
  , 'every'
  , 'findAsync'
  , 'find'
  , 'firstAsync'
  , 'first'
  , 'includesAsync'
  , 'includes'
  , 'matchAsync'
  , 'match'
  , 'reduceAsync'
  , 'reduce'
  , 'someAsync'
  , 'some'
  , 'lastAsync'
  , 'last'
  , 'toArrayAsync'
  , 'toArray'
  , 'toSetAsync'
  , 'toSet'
  ].sort()

  const actualExports = Object.keys(Index).sort()

  expect(actualExports).toEqual(expectedExports)
})
